<?php
/**
 * ABCampaignDataTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Moosend API
 *
 * TODO: Add a description
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * ABCampaignDataTest Class Doc Comment
 *
 * @category    Class */
// * @description ABCampaignData
/**
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class ABCampaignDataTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "ABCampaignData"
     */
    public function testABCampaignData()
    {
    }

    /**
     * Test attribute "ab_campaign_type"
     */
    public function testPropertyAbCampaignType()
    {
    }

    /**
     * Test attribute "ab_winner_selection_type"
     */
    public function testPropertyAbWinnerSelectionType()
    {
    }

    /**
     * Test attribute "delivered_on_a"
     */
    public function testPropertyDeliveredOnA()
    {
    }

    /**
     * Test attribute "delivered_on_b"
     */
    public function testPropertyDeliveredOnB()
    {
    }

    /**
     * Test attribute "html_content_b"
     */
    public function testPropertyHtmlContentB()
    {
    }

    /**
     * Test attribute "hours_to_test"
     */
    public function testPropertyHoursToTest()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "list_percentage"
     */
    public function testPropertyListPercentage()
    {
    }

    /**
     * Test attribute "plain_content_b"
     */
    public function testPropertyPlainContentB()
    {
    }

    /**
     * Test attribute "sender_b"
     */
    public function testPropertySenderB()
    {
    }

    /**
     * Test attribute "subject_b"
     */
    public function testPropertySubjectB()
    {
    }

    /**
     * Test attribute "web_location_b"
     */
    public function testPropertyWebLocationB()
    {
    }
}
