<?php
/**
 * BTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Moosend API
 *
 * TODO: Add a description
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * BTest Class Doc Comment
 *
 * @category    Class */
// * @description B
/**
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class BTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "B"
     */
    public function testB()
    {
    }

    /**
     * Test attribute "ab_version"
     */
    public function testPropertyAbVersion()
    {
    }

    /**
     * Test attribute "campaign_delivered_on"
     */
    public function testPropertyCampaignDeliveredOn()
    {
    }

    /**
     * Test attribute "campaign_id"
     */
    public function testPropertyCampaignId()
    {
    }

    /**
     * Test attribute "campaign_is_archived"
     */
    public function testPropertyCampaignIsArchived()
    {
    }

    /**
     * Test attribute "campaign_name"
     */
    public function testPropertyCampaignName()
    {
    }

    /**
     * Test attribute "campaign_subject"
     */
    public function testPropertyCampaignSubject()
    {
    }

    /**
     * Test attribute "from"
     */
    public function testPropertyFrom()
    {
    }

    /**
     * Test attribute "mailing_lists"
     */
    public function testPropertyMailingLists()
    {
    }

    /**
     * Test attribute "sent"
     */
    public function testPropertySent()
    {
    }

    /**
     * Test attribute "to"
     */
    public function testPropertyTo()
    {
    }

    /**
     * Test attribute "total_bounces"
     */
    public function testPropertyTotalBounces()
    {
    }

    /**
     * Test attribute "total_complaints"
     */
    public function testPropertyTotalComplaints()
    {
    }

    /**
     * Test attribute "total_forwards"
     */
    public function testPropertyTotalForwards()
    {
    }

    /**
     * Test attribute "total_link_clicks"
     */
    public function testPropertyTotalLinkClicks()
    {
    }

    /**
     * Test attribute "total_opens"
     */
    public function testPropertyTotalOpens()
    {
    }

    /**
     * Test attribute "total_unsubscribes"
     */
    public function testPropertyTotalUnsubscribes()
    {
    }

    /**
     * Test attribute "unique_forwards"
     */
    public function testPropertyUniqueForwards()
    {
    }

    /**
     * Test attribute "unique_link_clicks"
     */
    public function testPropertyUniqueLinkClicks()
    {
    }

    /**
     * Test attribute "unique_opens"
     */
    public function testPropertyUniqueOpens()
    {
    }
}
