<?php
/**
 * CampaignTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Moosend API
 *
 * TODO: Add a description
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * CampaignTest Class Doc Comment
 *
 * @category    Class */
// * @description Campaign
/**
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class CampaignTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "Campaign"
     */
    public function testCampaign()
    {
    }

    /**
     * Test attribute "ab_campaign_type"
     */
    public function testPropertyAbCampaignType()
    {
    }

    /**
     * Test attribute "ab_hours_to_test"
     */
    public function testPropertyAbHoursToTest()
    {
    }

    /**
     * Test attribute "ab_winner"
     */
    public function testPropertyAbWinner()
    {
    }

    /**
     * Test attribute "ab_winner_selection_type"
     */
    public function testPropertyAbWinnerSelectionType()
    {
    }

    /**
     * Test attribute "confirmation_to"
     */
    public function testPropertyConfirmationTo()
    {
    }

    /**
     * Test attribute "created_on"
     */
    public function testPropertyCreatedOn()
    {
    }

    /**
     * Test attribute "delivered_on"
     */
    public function testPropertyDeliveredOn()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "is_transactional"
     */
    public function testPropertyIsTransactional()
    {
    }

    /**
     * Test attribute "mailing_lists"
     */
    public function testPropertyMailingLists()
    {
    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {
    }

    /**
     * Test attribute "recipients_count"
     */
    public function testPropertyRecipientsCount()
    {
    }

    /**
     * Test attribute "scheduled_for"
     */
    public function testPropertyScheduledFor()
    {
    }

    /**
     * Test attribute "scheduled_for_timezone"
     */
    public function testPropertyScheduledForTimezone()
    {
    }

    /**
     * Test attribute "site_name"
     */
    public function testPropertySiteName()
    {
    }

    /**
     * Test attribute "status"
     */
    public function testPropertyStatus()
    {
    }

    /**
     * Test attribute "subject"
     */
    public function testPropertySubject()
    {
    }

    /**
     * Test attribute "total_bounces"
     */
    public function testPropertyTotalBounces()
    {
    }

    /**
     * Test attribute "total_complaints"
     */
    public function testPropertyTotalComplaints()
    {
    }

    /**
     * Test attribute "total_forwards"
     */
    public function testPropertyTotalForwards()
    {
    }

    /**
     * Test attribute "total_link_clicks"
     */
    public function testPropertyTotalLinkClicks()
    {
    }

    /**
     * Test attribute "total_opens"
     */
    public function testPropertyTotalOpens()
    {
    }

    /**
     * Test attribute "total_sent"
     */
    public function testPropertyTotalSent()
    {
    }

    /**
     * Test attribute "total_unsubscribes"
     */
    public function testPropertyTotalUnsubscribes()
    {
    }

    /**
     * Test attribute "unique_forwards"
     */
    public function testPropertyUniqueForwards()
    {
    }

    /**
     * Test attribute "unique_link_clicks"
     */
    public function testPropertyUniqueLinkClicks()
    {
    }

    /**
     * Test attribute "unique_opens"
     */
    public function testPropertyUniqueOpens()
    {
    }
}
