<?php
/**
 * CreatingADraftCampaignRequestTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Moosend API
 *
 * TODO: Add a description
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * CreatingADraftCampaignRequestTest Class Doc Comment
 *
 * @category    Class */
// * @description CreatingADraftCampaignRequest
/**
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class CreatingADraftCampaignRequestTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "CreatingADraftCampaignRequest"
     */
    public function testCreatingADraftCampaignRequest()
    {
    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {
    }

    /**
     * Test attribute "subject"
     */
    public function testPropertySubject()
    {
    }

    /**
     * Test attribute "sender_email"
     */
    public function testPropertySenderEmail()
    {
    }

    /**
     * Test attribute "reply_to_email"
     */
    public function testPropertyReplyToEmail()
    {
    }

    /**
     * Test attribute "is_ab"
     */
    public function testPropertyIsAb()
    {
    }

    /**
     * Test attribute "confirmation_to_email"
     */
    public function testPropertyConfirmationToEmail()
    {
    }

    /**
     * Test attribute "web_location"
     */
    public function testPropertyWebLocation()
    {
    }

    /**
     * Test attribute "mailing_lists"
     */
    public function testPropertyMailingLists()
    {
    }

    /**
     * Test attribute "segment_id"
     */
    public function testPropertySegmentId()
    {
    }

    /**
     * Test attribute "ab_campaign_type"
     */
    public function testPropertyAbCampaignType()
    {
    }

    /**
     * Test attribute "track_in_google_analytics"
     */
    public function testPropertyTrackInGoogleAnalytics()
    {
    }

    /**
     * Test attribute "dont_track_link_clicks"
     */
    public function testPropertyDontTrackLinkClicks()
    {
    }

    /**
     * Test attribute "subject_b"
     */
    public function testPropertySubjectB()
    {
    }

    /**
     * Test attribute "web_location_b"
     */
    public function testPropertyWebLocationB()
    {
    }

    /**
     * Test attribute "sender_email_b"
     */
    public function testPropertySenderEmailB()
    {
    }

    /**
     * Test attribute "hours_to_test"
     */
    public function testPropertyHoursToTest()
    {
    }

    /**
     * Test attribute "list_percentage"
     */
    public function testPropertyListPercentage()
    {
    }

    /**
     * Test attribute "ab_winner_selection_type"
     */
    public function testPropertyAbWinnerSelectionType()
    {
    }
}
