<?php
/**
 * ImportOperation19Test
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Moosend API
 *
 * TODO: Add a description
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * ImportOperation19Test Class Doc Comment
 *
 * @category    Class */
// * @description ImportOperation19
/**
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class ImportOperation19Test extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "ImportOperation19"
     */
    public function testImportOperation19()
    {
    }

    /**
     * Test attribute "completed_on"
     */
    public function testPropertyCompletedOn()
    {
    }

    /**
     * Test attribute "created_on"
     */
    public function testPropertyCreatedOn()
    {
    }

    /**
     * Test attribute "data_hash"
     */
    public function testPropertyDataHash()
    {
    }

    /**
     * Test attribute "email_notify"
     */
    public function testPropertyEmailNotify()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "mappings"
     */
    public function testPropertyMappings()
    {
    }

    /**
     * Test attribute "message"
     */
    public function testPropertyMessage()
    {
    }

    /**
     * Test attribute "skip_new_members"
     */
    public function testPropertySkipNewMembers()
    {
    }

    /**
     * Test attribute "started_on"
     */
    public function testPropertyStartedOn()
    {
    }

    /**
     * Test attribute "success"
     */
    public function testPropertySuccess()
    {
    }

    /**
     * Test attribute "total_duplicate"
     */
    public function testPropertyTotalDuplicate()
    {
    }

    /**
     * Test attribute "total_ignored"
     */
    public function testPropertyTotalIgnored()
    {
    }

    /**
     * Test attribute "total_inserted"
     */
    public function testPropertyTotalInserted()
    {
    }

    /**
     * Test attribute "total_invalid"
     */
    public function testPropertyTotalInvalid()
    {
    }

    /**
     * Test attribute "total_members"
     */
    public function testPropertyTotalMembers()
    {
    }

    /**
     * Test attribute "total_unsubscribed"
     */
    public function testPropertyTotalUnsubscribed()
    {
    }

    /**
     * Test attribute "total_updated"
     */
    public function testPropertyTotalUpdated()
    {
    }
}
