<?php
/**
 * SubscriberTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Moosend API
 *
 * TODO: Add a description
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * SubscriberTest Class Doc Comment
 *
 * @category    Class */
// * @description Subscriber
/**
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class SubscriberTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "Subscriber"
     */
    public function testSubscriber()
    {
    }

    /**
     * Test attribute "created_on"
     */
    public function testPropertyCreatedOn()
    {
    }

    /**
     * Test attribute "custom_fields"
     */
    public function testPropertyCustomFields()
    {
    }

    /**
     * Test attribute "email"
     */
    public function testPropertyEmail()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {
    }

    /**
     * Test attribute "removed_on"
     */
    public function testPropertyRemovedOn()
    {
    }

    /**
     * Test attribute "subscribe_method"
     */
    public function testPropertySubscribeMethod()
    {
    }

    /**
     * Test attribute "subscribe_type"
     */
    public function testPropertySubscribeType()
    {
    }

    /**
     * Test attribute "unsubscribed_from_id"
     */
    public function testPropertyUnsubscribedFromId()
    {
    }

    /**
     * Test attribute "unsubscribed_on"
     */
    public function testPropertyUnsubscribedOn()
    {
    }

    /**
     * Test attribute "updated_on"
     */
    public function testPropertyUpdatedOn()
    {
    }
}
