<?php
/**
 * CampaignsApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Moosend API
 *
 * TODO: Add a description
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use \Swagger\Client\Configuration;
use \Swagger\Client\ApiClient;
use \Swagger\Client\ApiException;
use \Swagger\Client\ObjectSerializer;

/**
 * CampaignsApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class CampaignsApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for aBTestCampaignSummary
     *
     * AB Test Campaign Summary.
     *
     */
    public function testABTestCampaignSummary()
    {
    }

    /**
     * Test case for activityByLocation
     *
     * Activity By Location.
     *
     */
    public function testActivityByLocation()
    {
    }

    /**
     * Test case for campaignSummary
     *
     * Campaign Summary.
     *
     */
    public function testCampaignSummary()
    {
    }

    /**
     * Test case for cloningAnExistingCampaign
     *
     * Cloning An Existing Campaign.
     *
     */
    public function testCloningAnExistingCampaign()
    {
    }

    /**
     * Test case for creatingADraftCampaign
     *
     * Creating A Draft Campaign.
     *
     */
    public function testCreatingADraftCampaign()
    {
    }

    /**
     * Test case for deletingACampaign
     *
     * Deleting A Campaign.
     *
     */
    public function testDeletingACampaign()
    {
    }

    /**
     * Test case for getAllCampaigns
     *
     * Get All Campaigns.
     *
     */
    public function testGetAllCampaigns()
    {
    }

    /**
     * Test case for getCampaignStatisticsWithPagingFiltered
     *
     * Get Campaign Statistics With Paging & Filtered.
     *
     */
    public function testGetCampaignStatisticsWithPagingFiltered()
    {
    }

    /**
     * Test case for getCampaignsByPage
     *
     * Get Campaigns By Page.
     *
     */
    public function testGetCampaignsByPage()
    {
    }

    /**
     * Test case for getCampaignsByPageAndPagesize
     *
     * Get Campaigns By Page And Pagesize.
     *
     */
    public function testGetCampaignsByPageAndPagesize()
    {
    }

    /**
     * Test case for gettingAllYourSenders
     *
     * Getting All Your Senders.
     *
     */
    public function testGettingAllYourSenders()
    {
    }

    /**
     * Test case for gettingCampaignDetails
     *
     * Getting Campaign Details.
     *
     */
    public function testGettingCampaignDetails()
    {
    }

    /**
     * Test case for gettingSenderDetails
     *
     * Getting Sender Details.
     *
     */
    public function testGettingSenderDetails()
    {
    }

    /**
     * Test case for linkActivity
     *
     * Link Activity.
     *
     */
    public function testLinkActivity()
    {
    }

    /**
     * Test case for schedulingACampaign
     *
     * Scheduling A Campaign.
     *
     */
    public function testSchedulingACampaign()
    {
    }

    /**
     * Test case for sendingACampaign
     *
     * Sending a campaign.
     *
     */
    public function testSendingACampaign()
    {
    }

    /**
     * Test case for testingACampaign
     *
     * Testing a campaign.
     *
     */
    public function testTestingACampaign()
    {
    }

    /**
     * Test case for unschedulingACampaign
     *
     * Unscheduling a campaign.
     *
     */
    public function testUnschedulingACampaign()
    {
    }

    /**
     * Test case for updatingADraftCampaign
     *
     * Updating A Draft Campaign.
     *
     */
    public function testUpdatingADraftCampaign()
    {
    }
}
