<?php
/**
 * MailingListsApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Moosend API
 *
 * TODO: Add a description
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use \Swagger\Client\Configuration;
use \Swagger\Client\ApiClient;
use \Swagger\Client\ApiException;
use \Swagger\Client\ObjectSerializer;

/**
 * MailingListsApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class MailingListsApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for creatingACustomField
     *
     * Creating a custom field.
     *
     */
    public function testCreatingACustomField()
    {
    }

    /**
     * Test case for creatingAMailingList
     *
     * Creating a mailing list.
     *
     */
    public function testCreatingAMailingList()
    {
    }

    /**
     * Test case for deletingAMailingList
     *
     * Deleting a mailing list.
     *
     */
    public function testDeletingAMailingList()
    {
    }

    /**
     * Test case for gettingAllActiveMailingLists
     *
     * Getting all active mailing lists.
     *
     */
    public function testGettingAllActiveMailingLists()
    {
    }

    /**
     * Test case for gettingAllActiveMailingListsWithPaging
     *
     * Getting all active mailing lists with paging.
     *
     */
    public function testGettingAllActiveMailingListsWithPaging()
    {
    }

    /**
     * Test case for gettingMailingListDetails
     *
     * Getting mailing list details.
     *
     */
    public function testGettingMailingListDetails()
    {
    }

    /**
     * Test case for removingACustomField
     *
     * Removing a custom field.
     *
     */
    public function testRemovingACustomField()
    {
    }

    /**
     * Test case for updatingACustomField
     *
     * Updating a custom field.
     *
     */
    public function testUpdatingACustomField()
    {
    }

    /**
     * Test case for updatingAMailingList
     *
     * Updating a mailing list.
     *
     */
    public function testUpdatingAMailingList()
    {
    }
}
