<?php
/**
 * SegmentsApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Moosend API
 *
 * TODO: Add a description
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use \Swagger\Client\Configuration;
use \Swagger\Client\ApiClient;
use \Swagger\Client\ApiException;
use \Swagger\Client\ObjectSerializer;

/**
 * SegmentsApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class SegmentsApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for addingCriteriaToSegments
     *
     * Adding criteria to segments.
     *
     */
    public function testAddingCriteriaToSegments()
    {
    }

    /**
     * Test case for creatingANewSegment
     *
     * Creating a new segment.
     *
     */
    public function testCreatingANewSegment()
    {
    }

    /**
     * Test case for deletingASegment
     *
     * Deleting A Segment.
     *
     */
    public function testDeletingASegment()
    {
    }

    /**
     * Test case for gettingSegmentDetails
     *
     * Getting segment details.
     *
     */
    public function testGettingSegmentDetails()
    {
    }

    /**
     * Test case for gettingSegmentSubscribers
     *
     * Getting segment subscribers.
     *
     */
    public function testGettingSegmentSubscribers()
    {
    }

    /**
     * Test case for gettingSegments
     *
     * Getting segments.
     *
     */
    public function testGettingSegments()
    {
    }

    /**
     * Test case for updatingASegment
     *
     * Updating a segment.
     *
     */
    public function testUpdatingASegment()
    {
    }

    /**
     * Test case for updatingSegmentCriteria
     *
     * Updating segment criteria.
     *
     */
    public function testUpdatingSegmentCriteria()
    {
    }
}
