<?php
/**
 * SubscribersApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Moosend API
 *
 * TODO: Add a description
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use \Swagger\Client\Configuration;
use \Swagger\Client\ApiClient;
use \Swagger\Client\ApiException;
use \Swagger\Client\ObjectSerializer;

/**
 * SubscribersApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class SubscribersApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for addingMultipleSubscribers
     *
     * Adding multiple subscribers.
     *
     */
    public function testAddingMultipleSubscribers()
    {
    }

    /**
     * Test case for addingSubscribers
     *
     * Adding subscribers.
     *
     */
    public function testAddingSubscribers()
    {
    }

    /**
     * Test case for getSubscriberByEmailAddress
     *
     * Get subscriber by email address.
     *
     */
    public function testGetSubscriberByEmailAddress()
    {
    }

    /**
     * Test case for getSubscriberById
     *
     * Get subscriber by id.
     *
     */
    public function testGetSubscriberById()
    {
    }

    /**
     * Test case for gettingSubscribers
     *
     * Getting subscribers.
     *
     */
    public function testGettingSubscribers()
    {
    }

    /**
     * Test case for removingASubscriber
     *
     * Removing a subscriber.
     *
     */
    public function testRemovingASubscriber()
    {
    }

    /**
     * Test case for removingMultipleSubscribers
     *
     * Removing multiple subscribers.
     *
     */
    public function testRemovingMultipleSubscribers()
    {
    }

    /**
     * Test case for unsubscribingSubscribersFromAccount
     *
     * Unsubscribing subscribers from account.
     *
     */
    public function testUnsubscribingSubscribersFromAccount()
    {
    }

    /**
     * Test case for unsubscribingSubscribersFromMailingList
     *
     * Unsubscribing subscribers from mailing list.
     *
     */
    public function testUnsubscribingSubscribersFromMailingList()
    {
    }

    /**
     * Test case for unsubscribingSubscribersFromMailingListAndASpecifiedCampaign
     *
     * Unsubscribing subscribers from mailing list and a specified campaign.
     *
     */
    public function testUnsubscribingSubscribersFromMailingListAndASpecifiedCampaign()
    {
    }

    /**
     * Test case for updatingASubscriber
     *
     * Updating a subscriber.
     *
     */
    public function testUpdatingASubscriber()
    {
    }
}
